/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.
    Created: xx.xx.2014

  ==============================================================================
*/

#include "Main.h"

#include "MainWindow.h"
#include "./components/MainComponent.h"

#include "./firmware/FirmwareTransfer.h"

#include "./style/LumatoneEditorLookAndFeel.h"

#include "./actions/EditorControlActions.h"|
#include "./actions/KeySelectionControlActions.h"

#include "./lumatone_editor_library/device/lumatone_controller.h"
#include "./lumatone_editor_library/device/activity_monitor.h"
#include "./lumatone_editor_library/graphics/view_constants.h"
#include "./lumatone_editor_library/palettes/colour_palette_file.h"

// #include "VelocityCurveDlgBase.h"
// #include "NoteOnOffVelocityCurveDialog.h"
#include "LumatoneMenu.h"

//==============================================================================
//
//MainContentComponent* TerpstraSysExApplication::getMainContentComponent() const
//{
//	jassert(mainWindow != nullptr);
//	return (MainContentComponent*)(mainWindow->getContentComponent());
//}

TerpstraSysExApplication::TerpstraSysExApplication()
    : firmwareDriver(LumatoneFirmwareDriver::HostMode::Driver)
    , state(juce::ValueTree(LumatoneEditorProperty::StateTree), firmwareDriver, &undoManager)
    , LumatoneEditorState::Controller(state)
{
    // Localisation
    juce::String localisation = getLocalisation(juce::SystemStats::getDisplayLanguage());
    juce::LocalisedStrings::setCurrentMappings(new juce::LocalisedStrings(localisation, false));
    juce::LocalisedStrings::getCurrentMappings()->setFallback(new juce::LocalisedStrings(BinaryData::engb_txt, false));

    loadColourPalettesFromFile();
}

//==============================================================================
void TerpstraSysExApplication::initialise(const juce::String& commandLine)
{
    // This method is where you should put your application's initialisation code..

    // commandLine parameters
    if (!commandLine.isEmpty())
    {
        auto commandLineParameters = getCommandLineParameterArray();

        for (auto commandLineParameter : commandLineParameters)
        {
            // ToDo switch on/off isomorphic mass assign mode

            // Try to open a config file
            if (juce::File::isAbsolutePath(commandLineParameter))
            {
                setCurrentFile(juce::File(commandLineParameter));
            }
            else
            {
                // If file name is with quotes, try removing the quotes
                if (commandLine.startsWithChar('"') && commandLine.endsWithChar('"'))
                    setCurrentFile(juce::File(commandLine.substring(1, commandLine.length() - 1)));
                    //setCurrentFile(commandLine.substring(1, commandLine.length()-1));
            }

            if (state.getCurrentFile().existsAsFile())
                break;	// There can only be one file, and the file name is supposed to be the last parameter
        }
    }

    commandManager.reset(new juce::ApplicationCommandManager());
    commandManager->registerAllCommandsForTarget(this);

    mainWindow.reset(new MainWindow(state, commandManager.get()));
    // mainWindow->restoreStateFromPropertiesFile(getPropertiesFile());
    mainWindow->setVisible(true);

    if (state.getCurrentFile().existsAsFile())
        resetToCurrentFile();
}

void TerpstraSysExApplication::shutdown()
{
    undoManager.clearUndoHistory();

    juce::LocalisedStrings::setCurrentMappings(nullptr);

    // Save state of main window
    //mainWindow->saveStateToPropertiesFile(state.propertiesFile.get());
    mainWindow = nullptr;

    savePropertiesFile();

    // juce::String stateStr =state.toString();
    // auto lines = juce::StringArray::fromLines(stateStr);
    // for (auto line : lines)
    // 	DBG(line);

    if (state.firmwareUpdateCompleted())
        FirmwareTransfer::exitLibSsh2();

    //delete firmwareDriver;

//	commandManager = nullptr;
}

//==============================================================================
void TerpstraSysExApplication::systemRequestedQuit()
{
    // This is called when the app is being asked to quit: you can ignore this
    // request and let the app carry on running, or call quit() to allow the app to close.

    // If there are changes: ask for save
    if (state.getHasChangesToSave())
    {
        juce::AlertWindow::showYesNoCancelBox(
            juce::AlertWindow::AlertIconType::QuestionIcon,
            "Quitting the application",
            "Do you want to save your changes?",
            "Yes", "No", "Cancel", nullptr,
            juce::ModalCallbackFunction::create([&](int retc)
            {
                if (retc == 0)
                {
                    // "Cancel". Do not quit.
                    return;
                }
                else if (retc == 1)
                {
                    // "Yes". Try to save. Cancel if unsuccessful
                    saveSysExMapping([&](bool success) { if (success) quit(); });
                }
                else
                {
                    // retc == 2: "No" -> end without saving
                    quit();
                }
            })
        );

        return;
    }

    quit();
}

void TerpstraSysExApplication::anotherInstanceStarted(const juce::String& commandLine)
{
    // When another instance of the app is launched while this one is running,
    // this method is invoked, and the commandLine parameter tells you what
    // the other instance's command-line arguments were.
}
//
//bool TerpstraSysExApplication::saveColourPalette(LumatoneEditorColourPalette& palette, juce::File pathToFile)
//{
//	bool success = false;
//
//	if (palette.hasBeenModified())
//	{
//		ValueTree paletteNode = palette.toValueTree();
//
//		// pathToFile is optional - default to path defined in palette
//		if (pathToFile == File())
//			pathToFile = File(palette.getPathToFile());
//
//        // If name changed, delete the old one
//        if (pathToFile.exists())
//        {
//            auto currentName = pathToFile.getFileName();
//            if (currentName != palette.getName())
//            {
//                pathToFile.deleteFile();
//            }
//        }
//
//		// New file
//		if (!pathToFile.existsAsFile())
//		{
//            String fileName = "UnnamedPalette";
//
//			if (palette.getName().isNotEmpty())
//                fileName = palette.getName();
//
//            pathToFile = state.getUserPalettesDirectory().getChildFile(fileName);
//
//			// Make sure filename is unique since saving happens automatically
//            // Sorry programmers, we're using cardinal numbers here, and the original is implicitly #1 ;)
//			int nameId = 1;
//			while (pathToFile.withFileExtension(PALETTEFILEEXTENSION).existsAsFile() && nameId < 999999)
//			{
//                auto fileNameToSave = fileName + "_" + String(++nameId);
//                pathToFile = state.getUserPalettesDirectory().getChildFile(fileNameToSave);
//			}
//		}
//
//		success = palette.saveToFile(pathToFile);
//
//		// TODO error handling?
//	}
//
//	// if (success)
//		// loadColourPalettesFromFile();
//
//	return success;
//}

void TerpstraSysExApplication::loadPropertiesFile()
{

}

void TerpstraSysExApplication::getAllCommands(juce::Array <juce::CommandID>& commands)
{
    juce::JUCEApplication::getAllCommands(commands);

    const juce::CommandID ids[] = {
        Lumatone::Menu::commandIDs::openSysExMapping,
        Lumatone::Menu::commandIDs::saveSysExMapping,
        Lumatone::Menu::commandIDs::saveSysExMappingAs,
        Lumatone::Menu::commandIDs::resetSysExMapping,
        Lumatone::Menu::commandIDs::importSysExMapping,

        Lumatone::Menu::commandIDs::selectAll,
        Lumatone::Menu::commandIDs::selectNone,

        Lumatone::Menu::commandIDs::deleteOctaveBoard,
        Lumatone::Menu::commandIDs::copyOctaveBoard,
        Lumatone::Menu::commandIDs::pasteOctaveBoard,
        Lumatone::Menu::commandIDs::pasteOctaveBoardChannels,
        Lumatone::Menu::commandIDs::pasteOctaveBoardNotes,
        Lumatone::Menu::commandIDs::pasteOctaveBoardColours,
        Lumatone::Menu::commandIDs::pasteOctaveBoardTypes,

        Lumatone::Menu::commandIDs::undo,
        Lumatone::Menu::commandIDs::redo,

        Lumatone::Menu::commandIDs::toggleKeyProperties,
        Lumatone::Menu::commandIDs::colourViewRGB,
        Lumatone::Menu::commandIDs::colourViewModel,

        Lumatone::Menu::commandIDs::aboutSysEx,
        Lumatone::Debug::commandIDs::toggleDeveloperMode
    };

    commands.addArray(ids, juce::numElementsInArray(ids));
}

void TerpstraSysExApplication::getCommandInfo(juce::CommandID commandID, juce::ApplicationCommandInfo& result)
{
    switch (commandID)
    {
    case Lumatone::Menu::commandIDs::openSysExMapping:
        result.setInfo("Load file mapping", "Open a Lumatone key mapping", "File", 0);
        result.addDefaultKeypress('o', juce::ModifierKeys::commandModifier);
        break;

    case Lumatone::Menu::commandIDs::saveSysExMapping:
        result.setInfo("Save mapping", "Save the current mapping to file", "File", 0);
        result.addDefaultKeypress('s', juce::ModifierKeys::commandModifier);
        break;

    case Lumatone::Menu::commandIDs::saveSysExMappingAs:
        result.setInfo("Save mapping as...", "Save the current mapping to new file", "File", 0);
        result.addDefaultKeypress('s', juce::ModifierKeys::commandModifier | juce::ModifierKeys::shiftModifier);
        break;

    case Lumatone::Menu::commandIDs::resetSysExMapping:
        result.setInfo("New", "Start new mapping. Clear all edit fields, do not save current edits.", "File", 0);
        result.addDefaultKeypress('n', juce::ModifierKeys::commandModifier);
        break;

    case Lumatone::Menu::commandIDs::importSysExMapping:
        result.setInfo("Import", "Import mapping from device.", "File", 0);
        result.addDefaultKeypress('i', juce::ModifierKeys::commandModifier);
        if (state.getConnectionState() != ConnectionState::ONLINE)
            result.setActive(false);
        break;

    case Lumatone::Menu::commandIDs::selectAll:
        result.setInfo("Select All", "Select All Keys", "Edit", 0);
        result.addDefaultKeypress('a', juce::ModifierKeys::ctrlModifier);
        break;

    case Lumatone::Menu::commandIDs::selectNone:
        result.setInfo("Select None", "Reset key selection status", "Edit", 0);
        result.addDefaultKeypress(juce::KeyPress::escapeKey, juce::ModifierKeys::noModifiers);
        result.addDefaultKeypress('a', juce::ModifierKeys::ctrlModifier | juce::ModifierKeys::altModifier);
        break;

    case Lumatone::Menu::commandIDs::deleteOctaveBoard:
        result.setInfo("Delete", "Delete section data", "Edit", 0);
        result.addDefaultKeypress(juce::KeyPress::deleteKey, juce::ModifierKeys::noModifiers);
        break;

    case Lumatone::Menu::commandIDs::copyOctaveBoard:
        result.setInfo("Copy section", "Copy current octave board data", "Edit", 0);
        result.addDefaultKeypress('c', juce::ModifierKeys::commandModifier);
        break;

    case Lumatone::Menu::commandIDs::pasteOctaveBoard:
        result.setInfo("Paste section", "Paste copied section data", "Edit", 0);
        result.addDefaultKeypress('v', juce::ModifierKeys::commandModifier);
        result.setActive(canPasteSubBoardData());
        break;

    case Lumatone::Menu::commandIDs::pasteOctaveBoardNotes:
        result.setInfo("Paste notes", "Paste copied section notes", "Edit", 0);
        result.addDefaultKeypress('v', juce::ModifierKeys::commandModifier | juce::ModifierKeys::shiftModifier);
        result.setActive(canPasteSubBoardData());
        break;

    case Lumatone::Menu::commandIDs::pasteOctaveBoardChannels:
        result.setInfo("Paste channels", "Paste copied section channels", "Edit", 0);
        result.addDefaultKeypress('v', juce::ModifierKeys::commandModifier | juce::ModifierKeys::altModifier);
        result.setActive(canPasteSubBoardData());
        break;

    case Lumatone::Menu::commandIDs::pasteOctaveBoardColours:
        result.setInfo("Paste colours", "Paste copied section colours", "Edit", 0);
        result.addDefaultKeypress('v', juce::ModifierKeys::altModifier);
        result.setActive(canPasteSubBoardData());
        break;

    case Lumatone::Menu::commandIDs::pasteOctaveBoardTypes:
        result.setInfo("Paste types", "Paste copied section key types", "Edit", 0);
        result.addDefaultKeypress('v', juce::ModifierKeys::altModifier | juce::ModifierKeys::shiftModifier);
        result.setActive(canPasteSubBoardData());
        break;

    case Lumatone::Menu::commandIDs::undo:
        result.setInfo("Undo", "Undo latest edit", "Edit", 0);
        result.addDefaultKeypress('z', juce::ModifierKeys::commandModifier);
        result.setActive(undoManager.canUndo());
        break;

    case Lumatone::Menu::commandIDs::redo:
        result.setInfo("Redo", "Redo latest edit", "Edit", 0);
        result.addDefaultKeypress('y', juce::ModifierKeys::commandModifier);
        result.addDefaultKeypress('z', juce::ModifierKeys::commandModifier + juce::ModifierKeys::shiftModifier);
        result.setActive(undoManager.canRedo());
        break;

    case Lumatone::Menu::commandIDs::toggleKeyProperties:
        result.setInfo("Key Properties", "Toggle Key Properties", "Keyboard", 0);
        // result.addDefaultKeypress('y', juce::ModifierKeys::commandModifier);
        // result.addDefaultKeypress('z', juce::ModifierKeys::commandModifier + juce::ModifierKeys::shiftModifier);
        result.setActive(true);
        result.setTicked(state.getBoolProperty(LumatoneEditorProperty::ShowKeyProperties, false));
        break;

    case Lumatone::Menu::commandIDs::colourViewRGB:
        result.setInfo("RGB", "", "Colour", 0);
        // result.addDefaultKeypress('y', juce::ModifierKeys::commandModifier);
        // result.addDefaultKeypress('z', juce::ModifierKeys::commandModifier + juce::ModifierKeys::shiftModifier);
        result.setActive(true);

        {
            auto mode = state.getStringProperty(LumatoneApplicationProperty::ColourMode, "");
            result.setTicked(mode == "RGB");
        }

        break;

    case Lumatone::Menu::commandIDs::colourViewModel:
        result.setInfo("Colour Model", "Redo latest edit", "Colour", 0);
        // result.addDefaultKeypress('y', juce::ModifierKeys::commandModifier);
        // result.addDefaultKeypress('z', juce::ModifierKeys::commandModifier + juce::ModifierKeys::shiftModifier);
        result.setActive(true);

        {
            auto mode = state.getStringProperty(LumatoneApplicationProperty::ColourMode, "");
            result.setTicked(mode.isEmpty() || mode.equalsIgnoreCase("ModelAdjusted") || mode.equalsIgnoreCase("None"));
        }
        break;

    case Lumatone::Menu::commandIDs::aboutSysEx:
        result.setInfo("About Lumatone Editor", "Shows version and copyright", "Help", 0);
        break;

    case Lumatone::Debug::commandIDs::toggleDeveloperMode:
        result.setInfo("Toggle Developer Mode", "Show/hide controls for tweaking internal parameters", "Edit", 0);
        result.addDefaultKeypress('m',
                   juce::ModifierKeys::ctrlModifier + juce::ModifierKeys::altModifier + juce::ModifierKeys::shiftModifier);
        result.setActive(true);
        break;

    default:
        juce::JUCEApplication::getCommandInfo(commandID, result);
        break;
    }
}

bool TerpstraSysExApplication::perform(const juce::ApplicationCommandTarget::InvocationInfo& info)
{
    switch (info.commandID)
    {
    case Lumatone::Menu::commandIDs::openSysExMapping:
        return openSysExMapping();
    case Lumatone::Menu::commandIDs::saveSysExMapping:
        return saveSysExMapping();
    case Lumatone::Menu::commandIDs::saveSysExMappingAs:
        return saveSysExMappingAs();
    case Lumatone::Menu::commandIDs::resetSysExMapping:
        return resetSysExMapping();
    case Lumatone::Menu::commandIDs::importSysExMapping:
        return onRequestDeviceConfig();

    case Lumatone::Menu::commandIDs::selectAll:
        return selectAllKeys();
    case Lumatone::Menu::commandIDs::selectNone:
        return resetKeySelection();

    case Lumatone::Menu::commandIDs::deleteOctaveBoard:
        return deleteSubBoardData();
    case Lumatone::Menu::commandIDs::copyOctaveBoard:
        return copySubBoardData();
    case Lumatone::Menu::commandIDs::pasteOctaveBoard:
        return pasteSubBoardData();
    case Lumatone::Menu::commandIDs::pasteOctaveBoardNotes:
    case Lumatone::Menu::commandIDs::pasteOctaveBoardChannels:
    case Lumatone::Menu::commandIDs::pasteOctaveBoardColours:
    case Lumatone::Menu::commandIDs::pasteOctaveBoardTypes:
        return pasteModifiedSubBoardData(info.commandID);

    case Lumatone::Menu::commandIDs::undo:
        return undo();

    case Lumatone::Menu::commandIDs::redo:
        return redo();

    case Lumatone::Menu::toggleKeyProperties:
        toggleKeyProperties();
        return true;
    case Lumatone::Menu::colourViewRGB:
        setColourMode(LumatoneApplicationState::ColourModes::RGB);
        return true;
    case Lumatone::Menu::colourViewModel:
        setColourMode(LumatoneApplicationState::ColourModes::ModelAdjusted);
        return true;

    case Lumatone::Menu::commandIDs::aboutSysEx:
        return aboutTerpstraSysEx();

    case Lumatone::Debug::commandIDs::toggleDeveloperMode:
        return toggleDeveloperMode();
    default:
        return juce::JUCEApplication::perform(info);
    }
}

bool TerpstraSysExApplication::openSysExMapping()
{
    fileChooser = std::make_unique<juce::FileChooser>("Open a Lumatone key mapping", state.getLastOpenedMappingsDirectory(), "*.ltn");
    fileChooser->launchAsync(juce::FileBrowserComponent::FileChooserFlags::canSelectFiles | juce::FileBrowserComponent::FileChooserFlags::openMode,
        [&](const juce::FileChooser& chooser)
        {
            juce::File result = chooser.getResult();
            if (!result.existsAsFile() || !result.hasFileExtension("ltn"))
                return;

            performAction(new SetCurrentFileAction(state, result));
        });

    return true;

}

bool TerpstraSysExApplication::saveSysExMapping(std::function<void(bool success)> saveFileCallback)
{
    if (state.getCurrentFile().getFileName().isEmpty())
        return saveSysExMappingAs(saveFileCallback);
    else
        return saveCurrentFile(saveFileCallback);
}

bool TerpstraSysExApplication::saveSysExMappingAs(std::function<void(bool)> saveFileCallback)
{
    fileChooser = std::make_unique<juce::FileChooser>("Lumatone Key Mapping Files", state.getLastOpenedMappingsDirectory(), "*.ltn");
    fileChooser->launchAsync(juce::FileBrowserComponent::FileChooserFlags::saveMode | juce::FileBrowserComponent::FileChooserFlags::warnAboutOverwriting,
        [this, saveFileCallback](const juce::FileChooser& chooser)
        {
            setCurrentFile(chooser.getResult());
            bool saved = saveCurrentFile();
            setHasChangesToSave(!saved);
            saveFileCallback(saved);
        });

    return true;
}

bool TerpstraSysExApplication::resetSysExMapping()
{
    setCurrentFile(juce::File());
    return true;
}

// Saves the current mapping to file, specified in state.getCurrentFile().
bool TerpstraSysExApplication::saveCurrentFile(std::function<void(bool success)> saveFileCallback)
{
    bool success = saveMappingToFile(state.getCurrentFile());
    saveFileCallback(success);
    return success;
}

bool TerpstraSysExApplication::selectAllKeys()
{
    return performAction(new SetKeySelectionAction(state, state.getMappingData()->getAllKeysMapped()));
}

bool TerpstraSysExApplication::resetKeySelection()
{
    return performAction(new SetKeySelectionAction(state, juce::Array<MappedLumatoneKey>()));
}

bool TerpstraSysExApplication::deleteSubBoardData()
{
    return performAction(((MainContentComponent*)(mainWindow->getContentComponent()))->createDeleteCurrentSectionAction());
}

bool TerpstraSysExApplication::copySubBoardData()
{
    return ((MainContentComponent*)(mainWindow->getContentComponent()))->copyCurrentSubBoardData();
}

bool TerpstraSysExApplication::pasteSubBoardData()
{
    return performAction(((MainContentComponent*)(mainWindow->getContentComponent()))->createPasteCurrentSectionAction());
}

bool TerpstraSysExApplication::pasteModifiedSubBoardData(juce::CommandID commandID)
{
    switch (commandID)
    {
    case Lumatone::Menu::pasteOctaveBoardNotes:
    case Lumatone::Menu::pasteOctaveBoardColours:
    case Lumatone::Menu::pasteOctaveBoardChannels:
    case Lumatone::Menu::pasteOctaveBoardTypes:
        // return performAction(((MainContentComponent*)(mainWindow->getContentComponent()))->createModifiedPasteCurrentSectionAction(commandID));
        return false;
    default:
        jassertfalse;
        return false;
    }
}

bool TerpstraSysExApplication::canPasteSubBoardData() const
{
    if (mainWindow != nullptr)
        return ((MainContentComponent*)(mainWindow->getContentComponent()))->canPasteCopiedSubBoard();
    return false;
}

bool TerpstraSysExApplication::undo()
{
    if (undoManager.undo())
    {
        setHasChangesToSave(true);
        return true;
    }
    else
        return false;
}

bool TerpstraSysExApplication::redo()
{
    if (undoManager.redo())
    {
        setHasChangesToSave(true);
        return true;
    }
    else
        return false;
}

bool TerpstraSysExApplication::toggleDeveloperMode()
{
    setDeveloperMode(!state.getInDeveloperMode());
    return true;
    // bool newMode = !propertiesFile->getBoolValue("DeveloperMode");
    // propertiesFile->setValue("DeveloperMode", newMode);
    // return ((MainContentComponent*)(mainWindow->getContentComponent()))->state.setDeveloperMode(newMode);
}

// bool TerpstraSysExApplication::generalOptionsDialog()
// {
// 	GeneralOptionsDlg* optionsWindow = new GeneralOptionsDlg();
// 	optionsWindow->setLookAndFeel(&lookAndFeel);

// 	DialogWindow::LaunchOptions launchOptions;
// 	launchOptions.content.setOwned(optionsWindow);
// 	launchOptions.content->setSize(480, 240);

// 	launchOptions.dialogTitle = "General options";
// 	launchOptions.dialogBackgroundColour = lookAndFeel.findColour(juce::ResizableWindow::backgroundColourId);
// 	launchOptions.escapeKeyTriggersCloseButton = true;
// 	launchOptions.useNativeTitleBar = false;
// 	launchOptions.resizable = true;

// 	DialogWindow* dw = launchOptions.launchAsync();
// 	dw->centreWithSize(480, 240);

// 	return true;
// }

// bool TerpstraSysExApplication::noteOnOffVelocityCurveDialog()
// {
// 	NoteOnOffVelocityCurveDialog* velocityCurveWindow = new NoteOnOffVelocityCurveDialog();
// 	velocityCurveWindow->setLookAndFeel(&lookAndFeel);

// 	int dlgWidth = propertiesFile->getIntValue("VelocityCurveWindowWidth", 648);
// 	int dlgHeight = propertiesFile->getIntValue("VelocityCurveWindowHeight", 424);

// 	DialogWindow::LaunchOptions launchOptions;
// 	launchOptions.content.setOwned(velocityCurveWindow);
// 	launchOptions.content->setSize(dlgWidth, dlgHeight);

// 	launchOptions.dialogTitle = "Note on/off velocity curve";
// 	launchOptions.dialogBackgroundColour = lookAndFeel.findColour(ResizableWindow::backgroundColourId);
// 	launchOptions.escapeKeyTriggersCloseButton = true;
// 	launchOptions.useNativeTitleBar = false;
// 	launchOptions.resizable = true;

// 	DialogWindow* dw = launchOptions.launchAsync();
// 	dw->centreWithSize(dlgWidth, dlgHeight);

// 	return true;
// }

// bool TerpstraSysExApplication::faderVelocityCurveDialog()
// {
// 	VelocityCurveDlgBase* velocityCurveWindow = new VelocityCurveDlgBase(LumatoneConfigTable::TableType::fader);
// 	velocityCurveWindow->setLookAndFeel(&lookAndFeel);

// 	int dlgWidth = propertiesFile->getIntValue("FaderVelocityCurveWindowWidth", 648);
// 	int dlgHeight = propertiesFile->getIntValue("FaderVelocityCurveWindowHeight", 424);

// 	DialogWindow::LaunchOptions launchOptions;
// 	launchOptions.content.setOwned(velocityCurveWindow);
// 	launchOptions.content->setSize(dlgWidth, dlgHeight);

// 	launchOptions.dialogTitle = "Fader velocity curve";
// 	launchOptions.dialogBackgroundColour = lookAndFeel.findColour(ResizableWindow::backgroundColourId);
// 	launchOptions.escapeKeyTriggersCloseButton = true;
// 	launchOptions.useNativeTitleBar = false;
// 	launchOptions.resizable = true;

// 	DialogWindow* dw = launchOptions.launchAsync();
// 	dw->centreWithSize(dlgWidth, dlgHeight);

// 	return true;
// }

// bool TerpstraSysExApplication::aftertouchVelocityCurveDialog()
// {
// 	VelocityCurveDlgBase* velocityCurveWindow = new VelocityCurveDlgBase(LumatoneConfigTable::TableType::afterTouch);
// 	velocityCurveWindow->setLookAndFeel(&lookAndFeel);

// 	int dlgWidth = propertiesFile->getIntValue("AftertouchVelocityCurveWindowWidth", 768);
// 	int dlgHeight = propertiesFile->getIntValue("AftertouchVelocityCurveWindowHeight", 424);

// 	DialogWindow::LaunchOptions launchOptions;
// 	launchOptions.content.setOwned(velocityCurveWindow);
// 	launchOptions.content->setSize(dlgWidth, dlgHeight);

// 	launchOptions.dialogTitle = "Aftertouch parameters";
// 	launchOptions.dialogBackgroundColour = lookAndFeel.findColour(ResizableWindow::backgroundColourId);
// 	launchOptions.escapeKeyTriggersCloseButton = true;
// 	launchOptions.useNativeTitleBar = false;
// 	launchOptions.resizable = true;

// 	DialogWindow* dw = launchOptions.launchAsync();
// 	dw->centreWithSize(dlgWidth, dlgHeight);

// 	return true;
// }


bool TerpstraSysExApplication::onRequestDeviceConfig()
{
    // if editing operations were done that have not been saved, give the possibility to save them
    if (state.getHasChangesToSave())
    {
        juce::AlertWindow::showYesNoCancelBox(
            juce::AlertWindow::AlertIconType::QuestionIcon,
            "Request configuration from device",
            "Lumatone's layout will now be imported. This will overwrite your unsaved changes. Do you want to save them first?",
            "Save to file", "Import anyway", "Cancel import", nullptr,
            juce::ModalCallbackFunction::create([&](int retc)
            {
                if (retc == 0)
                {
                    // "Cancel". Do not receive config, go offline
                    DBG("Layout import cancelled");
                    setEditMode(EditorMode::OFFLINE);
                    return;
                }
                else if (retc == 1)
                {
                    // "Yes". Try to save. Cancel if unsuccessful
                    saveSysExMapping([this](bool success)
                    {
                        if (success)
                            onRequestDeviceConfig();
                        else
                            DBG("Cancelled layout import");
                    });
                }
                else
                {
                    // retc == 2: "No" -> no saving, overwrite
                    DBG("Overwriting current edits");
                    setHasChangesToSave(false);
                    onRequestDeviceConfig();
                }
            })
        );

        return true;
    }

    // resetSysExMapping();
    requestCompleteDeviceConfig();

    return true;
}

//
//https://forum.juce.com/t/closing-dialog-windows-on-shutdown/27326/6
void TerpstraSysExApplication::setOpenDialogWindow(juce::DialogWindow* dialogWindowIn)
{
    dialogWindow.reset(dialogWindowIn);

    // attach callback to window to release std::unique_ptr when the window is closed
    juce::ModalComponentManager::getInstance()->attachCallback(dialogWindow.get(), juce::ModalCallbackFunction::create([&](int r)
    {
        dialogWindow.release();
    }));
}

bool TerpstraSysExApplication::aboutTerpstraSysEx()
{
    juce::String m;

    m << "Lumatone Editor" << juce::newLine
        << "Version " << getApplicationVersion() << juce::newLine
        << juce::newLine
        << "@ Hans Straub 2014 - 2021," << juce::newLine
        << "& Vincenzo Sicurella 2020 - 2022" << juce::newLine
        << juce::newLine
        << "Based on the program 'TerpstraSysEx' @ Dylan Horvath 2007" << juce::newLine
        << juce::newLine
        << "For help on using this program, or any questions relating to the Lumatone keyboard, go to:" << juce::newLine
        << juce::newLine
        << "https://www.lumatone.io/" << juce::newLine
        << juce::newLine
        << "Built " << juce::Time::getCompilationDate().toString(true, true, false, true)
        << " with " << juce::SystemStats::getOperatingSystemName() << juce::newLine
        << "on " << juce::SystemStats::getCpuModel() << juce::newLine
        << juce::SystemStats::getJUCEVersion();

    juce::DialogWindow::LaunchOptions options;
    auto textDisplay = new juce::TextEditor();
    //textDisplay->setLookAndFeel(&state.getEditorLookAndFeel());
    state.getEditorLookAndFeel().setupTextEditor(*textDisplay);
    textDisplay->setMultiLine(true, true);
    textDisplay->setText(m, juce::dontSendNotification);
    textDisplay->setFont(state.getAppFonts().getFont(LumatoneEditorFont::FranklinGothic));
    textDisplay->setReadOnly(true);
    textDisplay->setCaretVisible(false);
    options.content.setOwned(textDisplay);

    juce::Rectangle<int> area(0, 0, 400, 200);
    options.content->setSize(area.getWidth(), area.getHeight());

    //resizeLabelWithHeight(label, roundToInt(area.getHeight() * 0.24f));

    options.dialogTitle = "About Lumatone Editor";
    options.dialogBackgroundColour = state.getEditorLookAndFeel().findColour(LumatoneEditorColourIDs::HeaderBackground);

    options.escapeKeyTriggersCloseButton = true;
    options.useNativeTitleBar = false;
    options.resizable = false;


    auto dw = options.launchAsync();
    //dw->setLookAndFeel(&lookAndFeel);
    dw->centreWithSize(400, 260);

    setOpenDialogWindow(dw);

    return true;
}

//void LumatoneController::loadRandomMapping(int testTimeoutMs,  int maxIterations, int i)
//{
//    auto dir = juce::File::getSpecialLocation(juce::File::SpecialLocationType::userDocumentsDirectory).getChildFile("Lumatone Editor").getChildFile("Mappings");
//    auto mappings = dir.findChildFiles(juce::File::TypesOfFileToFind::findFiles, true);
//    auto numfiles = mappings.size();
//    auto r = juce::Random();
//
//    auto fileIndex = r.nextInt(numfiles-1);
//    auto file = mappings[fileIndex];
//
//    if (file.exists() && file.hasFileExtension(".ltn"))
//    {
//        DBG("Found " + juce::String(numfiles) + " files, loading " + file.getFileName());
//        juce::MessageManager::callAsync([file]() { TerpstraSysExApplication::getApp().setCurrentFile(file); });
//    }
//
////    if (i < maxIterations)
////        Timer::callAfterDelay(testTimeoutMs, [&]() { loadRandomMapping(testTimeoutMs, maxIterations, i + 1); });
////    else
////        DBG("Finished random mappings test.");
//}

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION(TerpstraSysExApplication)
